export const ACTION_CARD_PHASES: Record<string, string[]> = {
  act_luz:      ['discussion', 'voting'],
  act_lustr:    ['round_reveal', 'discussion'],
  act_bribe:    ['discussion'],
  act_breath:   ['discussion'],
  act_prof:     ['discussion'],
  act_ban:      ['discussion'],
  act_bavovna:  ['discussion'],
  act_human:    ['discussion'],
  act_martial:  ['voting'],
  act_kum:      ['voting'],
  act_quar:     ['discussion'],
  act_reform:   ['discussion'],
  act_blackout: ['voting'],
  act_deport:   ['discussion'],
  act_donat:    ['discussion'],
  act_nat:      ['discussion'],
  act_refut:    ['voting_result'],
}
